[package]
name = "password-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
csv = "1.4.0"
inquire = "0.9.1"
rand = "0.9.2"
serde = "1.0.228"
serde_json = "1.0.148"
toml = { version = "0.9.10", features = ["serde"] }
