[package]
name = "password-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
inquire = "0.9.1"
serde = "1.0.228"
toml = { version = "0.9.10", features = ["serde"] }
